version: 2
jobs:
  build:
    working_directory: ~/cli
    docker:
      - image: docker:17.05
    steps:
      - run:
          name: "Install Git and SSH"
          command: |
            apk add -U git openssh
      - checkout
      - setup_remote_docker
      - run:
          name: "Lint"
          command: |
            docker build -f dockerfiles/Dockerfile.lint --tag cli-linter .
            docker run cli-linter
      - run:
          name: "Build and Unit Test"
          command: |
            docker build -f dockerfiles/Dockerfile.ci --tag cli-builder .
            docker run cli-builder
      - run:
          name: "Vendor"
          command: |
            docker run cli-builder make vendor
