version: 2
jobs:
  build:
    working_directory: ~/cli
    docker:
      - image: docker:17.04
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f dockerfiles/Dockerfile.ci .
