version: '3.3'

services:
  registry:
    image: 'registry:2'

  engine:
      image: 'docker:${TEST_ENGINE_VERSION:-edge-dind}'
      privileged: true
      command: ['--insecure-registry=registry:5000']
